### ISSUE TITLE
Help with Installation of GoodNeighbor

### ISSUE THREAD

**Issue by DallasCowboy** [zackproser/goodneighbor#1]
Hi Zack Proser,

Thanks for open-sourcing this awesome project.

I am trying to install this on a Centos system. (only wanted to build and run the provided images,)

However I am getting errors when I run the command "docker-compose build && docker-compose up"

The log file,  /app/grand-central-station/goodneighbor-admin-ui/npm-debug.log, was not created.

Attached is the output after running this command. 

Running with following versions:
a.   Centos 7
b.   Docker version 1.15.0
c.   node.js version v8.4.0
d.   npm version v5.3.0
e.   MongoDB 3.4.7

I would appreciate it if you could kindle let me know if I need to do something different.

Thanks!

[Goodneighbor_Error.txt](https://github.com/zackproser/goodneighbor/files/1260284/Goodneighbor_Error.txt)

**Comment by echarrod** [comment]
Hi @DallasCowboy & @zackproser, 

I have a similar setup and exactly the same error - "Cannot find module 'ora'"

Just wondering if you managed to work out what was wrong?

Many Thanks

**Comment by zackproser** [comment]
Hi, 

The docker compose script is just provided as a quick way to run everything on your local machine and get a sense of how the components fit together. 

I'm going to try to find the time to put together an installation script to include, but in the meantime the rough steps for getting it running on your staging / prod machine: 

-  mongorestore db-seeder/goodneighbor-production-data folder 
-  cd good-neighbor-clustered  && npm i 
-  cd ../grand-central-station && npm i 
- look in the Dockerfile for ENV variables and pass them to node on startup 

You can keep the defaults as they are to start with, e.g: 

ENV GRAND_CENTRAL_STATION_PORT=3100 ENV FALLEN_AVATAR_RECOVERY_INTERVAL_MILLISECONDS=12000 node grand-central-station.js

**Comment by zackproser** [comment]
@DallasCowboy @echarrod  There is now an install.sh script included in the root of the project that should make it easier to get up and running.
